import type { Metadata } from "next";

import "./globals.css";
import { alexandria, generalSans } from "./font";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${generalSans.variable} ${alexandria.variable} antialiased`}>
                <div className="max-w-[1440px] mx-auto">{children}</div>
            </body>
        </html>
    );
}
